server:
  port: 4040
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    url: jdbc:mysql://localhost:3306/tieto_customer
    username: root
   
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true